VRHIKKY/VketCloudSDK_Documents

docs/Unity/HEOTweetTrigger.ja.md

HEOTweetTriggerに関する記述を追加しました。
heliodor関連の記述の必要性があるため、簡潔に注意点のみ記述しておきました。
ページを表示するにはymlの更新が必要かと思います。

HEOTweetTriggerに関する記述の追加

---

index.html

rename 3.1 to 4.1 

---

docs/hs/hs_component.en.md
docs/hs/hs_component.ja.md
docs/hs/hs_system_function_textchat.en.md
docs/hs/hs_system_function_textchat.ja.md
mkdocs.yml

ここのリポジトリには、初プルリクです。
よろしくお願いします。
- OnReceiveTextChat：ヘリスクリプトのコンポーネントページの修正
- hsTextChatOutput：組み込み関数に「テキストチャット」ページを追加、ページ内にドキュメント追加

v4.0 で追加されたテキストチャット系機能のドキュメント追加

---

docs/heliport/heliport_overview.en.md
docs/heliport/heliport_overview.ja.md
docs/heliport/heliport_useChatGpt.en.md
docs/heliport/heliport_useChatGpt.ja.md
mkdocs.yml

https://hikky.atlassian.net/browse/PHEL-151
- @yunoda-3DCG 執筆内容並びに更新内容が規約にそぐわない、あるいはPRに必要事項が不足している場合などはご教示いただけますと幸いです。
- @hasegawa-HIKKY 素人目に見て問題ないかご確認ください
- @otsuka-kentaro @d-hky @ikasekai 内容に問題ないかレビューいただけますと幸いです。

Heliport.js(ChatGPT)のドキュメント追加

---

docs/index.en.md
docs/index.ja.md

Ver4.8: 「はじめに」にリリースノートとチェンジログの案内を追加 

---

docs/WorldMakingGuide/HEOExporter_Tutorial.en.md
docs/WorldMakingGuide/HEOExporter_Tutorial.ja.md

Ver.5.4: HEOExporter_Tutorialの画像リンクを修正

---

docs/changelog/changelog-4.8.en.md
docs/changelog/changelog-4.8.ja.md

Ver5.4: チェンジログにてVer4.8のページが開けない問題の修正

---

requirements.txt

Ver4.8: デプロイ環境のmkdocs-static-i18nバージョンを固定

---

docs/changelog/changelog-4.8.en.md
docs/changelog/changelog-4.8.ja.md
docs/changelog/changelog-5.4.en.md
docs/changelog/changelog-5.4.ja.md

#165 から 4.8 / 5.4のチェンジログフォーマットの改善を取り出したものです

Ver5.4：チェンジログフォーマットを改善

---

mkdocs.yml

Ver4.8: mkdocs整備

---

mkdocs.yml

Ver9.0: mkdocs整備

---

mkdocs.yml

HEOComponentの並び順をアルファベット順に、Actionについてカテゴリごとに分類して整理を行いました。
また、整備中・廃止された機能のページについては一覧からのコメントアウトを行いました。

mkdocsの並び順の整列、整備中・廃止されたページを明記

---

docs/changelog/changelog-9.0.en.md
docs/changelog/changelog-9.0.ja.md

Ver9.0: チェンジログのリンクを絶対パスに変更

---

docs/changelog/changelog-4.8.en.md
docs/changelog/changelog-4.8.ja.md

Ver4.8: チェンジログのリンクを絶対パスに変更

---

docs/changelog/changelog-5.4.ja.md

.mdになっている部分を.htmlに変更

---

docs/FirstStep/BuildAndRun.en.md
docs/FirstStep/BuildAndRun.ja.md
docs/changelog/changelog-5.4.en.md
docs/changelog/changelog-5.4.ja.md

Ver4.8: キャッシュクリアについての記述を変更

---

docs/FirstStep/BuildAndRun.en.md
docs/FirstStep/BuildAndRun.ja.md
docs/changelog/changelog-5.4.en.md
docs/changelog/changelog-5.4.ja.md

Ver9.0: キャッシュクリアについての記述を変更

---

docs/changelog/changelog-5.4.en.md
docs/changelog/changelog-5.4.ja.md
docs/hs/hs_string.en.md
docs/hs/hs_string.ja.md

(cherry picked from commit 7bc64147196165e43c28adbd60a0ad83bd98a21e)

V4.8: %演算子に関するサンプルコードを更新

---

docs/HEOComponents/HEOPlane.en.md
docs/HEOComponents/HEOPlane.ja.md

Ver9.0: HEOPlane: jpgを使用-->pngを使用に修正、ENのスタイル崩れを修正

---

docs/HEOComponents/HEOPlane.en.md
docs/HEOComponents/HEOPlane.ja.md

Ver5.4: HEOPlane: jpgを使用-->pngを使用に修正、ENのスタイル崩れを修正

---

docs/WorldMakingGuide/PropAnimation.en.md
docs/WorldMakingGuide/PropAnimation.ja.md
docs/WorldMakingGuide/PropAnimation_TroubleShooting.en.md
docs/WorldMakingGuide/PropAnimation_TroubleShooting.ja.md
docs/changelog/changelog-5.4.en.md

Ver5.4: オブジェクトを動かす: 英訳を追加

---

docs/WorldMakingGuide/OcclusionCulling.en.md
docs/changelog/changelog-5.4.en.md

(cherry picked from commit c28f75f48aac98a4635f74a1e66c293bd0869cb2)

Ver5.4: オクルージョンカリング：英訳を追加

---

docs/HEMAnimationConverter/AnimationConverter.en.md
docs/changelog/changelog-5.4.en.md

(cherry picked from commit 84cffb2084a214d58b0badc0357bd49c815e0302)

Ver5.4: AnimationConverter: 英訳を追加

---

docs/changelog/changelog-12.3.en.md
docs/changelog/changelog-12.3.ja.md
docs/hs/hs_class_player.en.md
docs/hs/hs_class_player.ja.md
docs/hs/hs_overview.en.md
docs/hs/hs_overview.ja.md

Documentation, Enhancement
___
- HeliScriptのドキュメントに、コンストラクタ内でのPlayerクラス関数の呼び出しを禁止する仕様変更についての情報を追加しました。
- Playerクラスの関数をコンストラクタ内で呼び出すことができなくなったため、初期化方法の例を追加しました。
- 英語版と日本語版のドキュメント両方に変更を適用しました。
___
<tr>
<td>
<details>
<summary><strong>changelog-12.3.en.md</strong><dd><code>HeliScriptの更新情報にPlayerクラス関数の仕様変更を追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/changelog/changelog-12.3.en.md
- HeliScriptの更新情報に、コンストラクタ内でのPlayerクラス関数の仕様変更に関する情報を追加
</details>
</td>
<td><a …

hs_player, hs_overview: コンストラクタにおけるPlayerクラス関数の仕様変更を追記

---

docs/AboutVketCloudSDK/OperatingEnvironment.en.md
docs/AboutVketCloudSDK/OperatingEnvironment.ja.md
docs/AboutVketCloudSDK/SetupSDK_external.en.md
docs/AboutVketCloudSDK/SetupSDK_external.ja.md
docs/changelog/changelog-12.3.en.md
docs/changelog/changelog-12.3.ja.md
docs/heoexporter/he_align_unity_to_vketcloud.en.md
docs/heoexporter/he_align_unity_to_vketcloud.ja.md

Documentation, Enhancement
___
- Unityの動作環境とStandard Shaderの品質設定に関する必須手順を追加しました。
- VketCloudSDKのインストール手順に関するドキュメントを更新しました。
- UnityとVketCloudの見た目を揃えるための設定方法にStandard Shaderの品質設定を追加しました。
- チェンジログにStandard Shaderの品質設定に関する必須手順の追加を含む複数のページの編集情報を追加しました。
___
<tr>
<td>
<details>
<summary><strong>OperatingEnvironment.en.md</strong><dd><code>Unityの動作環境とStandard Shaderの品質設定の更新</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/AboutVketCloudSDK/OperatingEnvironment.en.md
<li>Unityのサポートバージョンとインストール手順の説明を更新<br> <li> …

動作環境、SDK導入： 必須設定としてStandard Shader品質の変更を追加

---

docs/WorldMakingGuide/Collider.en.md
docs/WorldMakingGuide/Collider.ja.md

Documentation
___
- `HEOCollider`へのリンクが間違っていたため、正しいパスに修正しました。
- SDK Ver12.3で発生している、特定のコンポーネントが付いたオブジェクトのみ存在するワールドでプレイヤーが空中に浮遊する問題に関する注意書きを更新しました。
___
<tr>
<td>
<details>
<summary><strong>Collider.en.md</strong><dd><code>HEOColliderリンクの修正と注意書きの更新</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/WorldMakingGuide/Collider.en.md
- `HEOCollider`のリンクを修正しました。
- プレイヤーが空中に浮遊する問題に関する注意書きを更新しました。
</details>
</td>
<td><a …

Collider: リンク修正

---

docs/HEOComponents/HEOActivity.en.md
docs/HEOComponents/HEOActivity.ja.md
docs/HEOComponents/HEOVideoTrigger.en.md
docs/HEOComponents/HEOVideoTrigger.ja.md
docs/SDKTools/VKCActivityExporter.en.md
docs/SDKTools/VKCActivityExporter.ja.md
docs/changelog/changelog-12.3.en.md
docs/changelog/changelog-12.3.ja.md

Documentation, Enhancement
___
- HEOActivityのドキュメントに"アクティビティの自作について"のセクションを追加しました。
- HEOVideoTriggerのドキュメントにSDK Ver12.3.4以降での使用に関する注意を追加しました。
- VKC Activity Exporterのドキュメントを更新し、HEOVideoTriggerの使用に関する注意を追加しました。
- 変更履歴にSDK12.3.4以降でのHEOVideoTrigger使用に関する注意を追加しました。
___
<tr>
<td>
<details>
<summary><strong>HEOActivity.en.md</strong><dd><code>HEOActivity英語版ドキュメントの更新</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

VKC Activity Exporter: SDK12.3.4以降にてHEOVideoTrigger使用の際の注意を追加

---

docs/AboutVketCloudSDK/SetupSDK_external.en.md

Documentation
___
- `SetupSDK_external.en.md`ファイルにおいて、画像リンクのパスを修正しました。
- 修正前は画像が正しく表示されない問題がありましたが、`heoexporter`ディレクトリへのパスに修正することで解決しました。
___
<tr>
<td>
<details>
<summary><strong>SetupSDK_external.en.md</strong><dd><code>画像リンクのパスを`heoexporter`ディレクトリに修正</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/AboutVketCloudSDK/SetupSDK_external.en.md
- 画像リンクのパスを修正しました。
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/346/files#diff-a172544c0862a3e516475728a1e67d89e1 …

SetupSDK_external: 画像リンクを修正

---

docs/changelog/changelog-12.3.en.md
docs/changelog/changelog-12.3.ja.md
docs/hs/hs_class_item.en.md
docs/hs/hs_class_item.ja.md

Documentation
___
- SetUVOffset関数の説明を更新し、UV座標の原点が左上であることに関する警告を追加しました。
- 英語と日本語のチェンジログにSetUVOffsetのUV原点に関する注意事項を追記しました。
- IsPlay関数の異なる戻り値に関する注意を警告に変更しました。
___
<tr>
<td>
<details>
<summary><strong>changelog-12.3.en.md</strong><dd><code>Added UV Origin Caution to Changelog (English)</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/changelog/changelog-12.3.en.md
<li>Added a caution note about the UV origin position when using <br>SetUVOffset.<br>
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/377/files#diff-2edecac36a9625444684d775e5d5182add66440e669c835093fc7 …

hs_item: SetUVOffsetの原点に関する補足を追記

---

custom_theme/404.html
mkdocs.yml

修正したい内容：Redirect URLの機能を追加, i18nを更新したせいで、"/ja"を含むURLにアクセスすると404を返すようになった。
なので、以下URLにアクセスした際に、日本語ページにredirectできるように実装する
http://127.0.0.1:8000/ja/index.html
以下例1：
アクセスするURL
http://127.0.0.1:8000/ja/index.html
Redirect先URL
http://127.0.0.1:8000/index.html
以下例2：
アクセスするURL
http://127.0.0.1:8000/ja/Actions/ActionsOverview.html
Redirect先URL
http://127.0.0.1:8000/Actions/ActionsOverview.html
___
Enhancement, Documentation
___
- 404ページにJavaScriptを用いたリダイレクト機能を追加し、特定のパスアクセス時に適切なページへ自動的にリダイレクトするように実装
- チェンジログ12.3のドキュメント内リンクを更新し、不要な言語パスを削除
- mkdocsの設定を更新し、404ページを静的テンプレートとして組み込み、デフォルト言語設定を日本語に変更
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
<tr>
<td>
<details> …

/jaのURLにアクセスした際に、/jaなしのURLにredirectできるようにjsで実装する

---

docs/FirstStep/WorldBasicComponents.en.md
docs/FirstStep/WorldBasicComponents.ja.md

オブジェクト名の最新化および、詳細についてはVket Cloud Settingsの概要ページに飛ばすように変更
またコンポーネントの紹介ではなくオブジェクトの紹介のため、各所の記載を修正
___
Documentation
___
- 英語版と日本語版のドキュメントにおいて、オブジェクト名を最新のものに更新。
- 詳細設定についてのリンクを追加。
- 記載内容を一部修正し、より正確な情報を提供。
___
<tr>
<td>
<details>
<summary><strong>WorldBasicComponents.en.md</strong><dd><code>英語版: オブジェクト名と詳細リンクの更新</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/FirstStep/WorldBasicComponents.en.md
- オブジェクト名の更新
- 詳細ページへのリンク追加
- …

ワールドの基本要素: オブジェクト名の最新化

---

docs/WorldMakingGuide/AvatarFile.en.md
docs/WorldMakingGuide/AvatarFile.ja.md

古いコンポーネント名の記載修正と、Adavanced設定の変更方法を追記
英語ページは仮

AvatarFile: 'HEOWorldSetting' から ' Avatar Settings'へ記載修正

---

docs/WorldMakingGuide/PropAnimation.en.md
docs/WorldMakingGuide/PropAnimation.ja.md

Documentation
___
- 英語版および日本語版のPropAnimationガイドにおける画像リンクのファイル名を修正しました。
___
<tr>
<td>
<details>
<summary><strong>PropAnimation.en.md</strong><dd><code>画像リンクのファイル名修正 (英語版)</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/WorldMakingGuide/PropAnimation.en.md
- 画像リンクのファイル名を修正
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/389/files#diff-f8eeef59c913081bd78c862a326d05422ef6517 …

PropAnimation: 画像リンクを修正

---

docs/hs/hs_class_item.ja.md
docs/hs/hs_list.en.md
docs/hs/hs_list.ja.md

Documentation
___
- `SetUVOffset` メソッドの引数名のタイポを修正しました。
- `CopyFrom` メソッドの引数名のタイポを修正しました（英語版、日本語版）。
- コードブロックのフォーマットを調整しました（英語版、日本語版）。
___
<tr>
<td>
<details>
<summary><strong>hs_class_item.ja.md</strong><dd><code>`SetUVOffset` メソッドの引数名のタイポ修正</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/hs/hs_class_item.ja.md
- `SetUVOffset` メソッドの引数名のタイポを修正
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/392/files#diff-f6aecf9ef9a5d9d3b69498c7fbd55 …

HeliScript関連ドキュメントのタイポ・フォーマットを修正

---

docs/WorldMakingGuide/UnityGuidelines.en.md
docs/WorldMakingGuide/UnityGuidelines.ja.md
docs/changelog/changelog-12.3.ja.md

Documentation
___
- `UnityGuidelines.ja.md`に使用可能な文字に関する仕様を追記。
- `UnityGuidelines.en.md`および`UnityGuidelines.ja.md`の複数のセクションで`caution`を`warning`に変更。
- `changelog-12.3.ja.md`に使用可能な文字に関する仕様の追記を追加。
___
<tr>
<td>
<details>
<summary><strong>UnityGuidelines.en.md</strong><dd><code>Update caution to warning in Unity Guidelines (EN)</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/WorldMakingGuide/UnityGuidelines.en.md
- Changed `caution` to `warning` in multiple sections.
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/395/files#diff-104299be9d4b84dd01b74b560c6717eb208a1c8859bed98cbe2899602d78a …

UnityGuideLines: 使用可能な文字に関する仕様を追記し、caution --> warningに変更

---

docs/WorldMakingGuide/AvatarFile.en.md
docs/WorldMakingGuide/AvatarFile.ja.md
docs/changelog/changelog-12.3.en.md
docs/changelog/changelog-12.3.ja.md

Documentation
___
- AvatarFileのドキュメントにおいて、ボーン名の表記をスネークケースからキャメルケースに修正しました。
- 英語版と日本語版の両方のドキュメントで、例を更新しました。
___
<tr>
<td>
<details>
<summary><strong>AvatarFile.en.md</strong><dd><code>ボーン名表記をキャメルケースに修正 (英語版)</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/WorldMakingGuide/AvatarFile.en.md
- ボーン名の表記をスネークケースからキャメルケースに修正
- 例を更新
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/419/files#diff-cbe1b08af80cd7 …

Avatarfile: ボーン名表記をCamelCase表記に修正

---

docs/changelog/changelog-13.4.en.md
docs/changelog/changelog-13.4.ja.md
docs/hs/hs_class_player.en.md
docs/hs/hs_class_player.ja.md

Documentation
___
- `Player`クラスに新しい関数`ResetVelocity`を追加したことをドキュメントに反映。
- 英語および日本語の変更ログに2024年7月12日の更新エントリを追加。
- `ResetVelocity`関数の詳細を英語および日本語のドキュメントに追加。
___
<tr>
<td>
<details>
<summary><strong>changelog-13.4.en.md</strong><dd><code>Added changelog entry for ResetVelocity function in Player class.</code></dd></summary>
<hr>
<li>Added entry for July 12, 2024 update.<br> <li> Documented addition of <code>ResetVelocity</code> function in <code>Player</code> class.<br>
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/426/files#diff-14c8c02824d74eee1b43874bee086055865ce98e61bcf95f26f17429d …

hs_class_player : ResetVelocity()を追加

---

docs/FirstStep/BuildAndRun.en.md
docs/FirstStep/BuildAndRun.ja.md
docs/changelog/changelog-13.4.en.md
docs/changelog/changelog-13.4.ja.md
docs/hs/hs_overview.en.md
docs/hs/hs_overview.ja.md
docs/troubleshooting/BuildError.en.md
docs/troubleshooting/BuildError.ja.md

Documentation
___
- ビルドと実行、HeliScript概要、トラブルシューティングの各セクションにHeliScriptエラーのトラブルシューティング方法を追加。
- デバッグモードを有効にする方法とブラウザコンソールでエラーを確認する手順を記載。
- changelogにHeliScriptエラー表示方法に関する注意を追記。
___
<tr>
<td>
<details>
<summary><strong>BuildAndRun.en.md</strong><dd><code>Added instructions for troubleshooting HeliScript errors in Build and </code><br><code>Run.</code></dd></summary>
<hr>
docs/FirstStep/BuildAndRun.en.md
<li>Added caution note about troubleshooting HeliScript errors.<br> <li> Provided instructions to enable Debug Mode and check Browser Console.<br>
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/427/files#diff-873b0c8978f3 …

hs_overview, BuildError, BuildAndRun : HeliScriptエラーの表示方法に関する注意を追記

---

docs/VketCloudSettings/BasicSettings.en.md
docs/VketCloudSettings/BasicSettings.ja.md
docs/changelog/changelog-13.4.en.md
docs/changelog/changelog-13.4.ja.md

Documentation
___
- `BasicSettings`の英語および日本語ドキュメントに`File Deployment Mode`の説明を追加
- `File Deployment Config`ページへのリンクを追加
- 2024年7月26日の更新内容を英語および日本語の変更ログに追加
___
<tr>
<td>
<details>
<summary><strong>BasicSettings.en.md</strong><dd><code>`File Deployment Mode`の説明を追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/VketCloudSettings/BasicSettings.en.md
- `File Deployment Mode`の説明を追加
- `File Deployment Config`ページへのリンクを追加
</details>
</td>
<td><a …

File Deployment Modeの説明を追加

---

.github/workflows/mkdocs-deploy.yml

Enhancement, Configuration changes
___
- GitHub Actionsの`actions/checkout`のバージョンをv2からv3に更新
- Dockerイメージのビルドとデプロイジョブの設定を追加
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>mkdocs-deploy.yml</strong><dd><code>GitHub Actionsの設定ファイルを更新し、デプロイジョブを追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/mkdocs-deploy.yml
<li><code>actions/checkout</code>のバージョンをv2からv3に更新<br> <li> Dockerイメージのビルドステップを追加<br> <li> デプロイジョブの設定を追加<br>
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/446/files#diff-18315f76d1 …

mkdocs-deployのcheckoutをv2ではなくv3を使用

---

docs/VKCComponents/VKCHEOCorrespondenceTable.en.md
docs/VKCComponents/VKCHEOCorrespondenceTable.ja.md
docs/changelog/changelog-13.4.en.md
docs/changelog/changelog-13.4.ja.md
mkdocs.yml

Documentation
___
- 「VKC/HEO Components Overview」ページのタイトル変更
- 日本語版にItemとNodeの詳細説明を追加
- 英語版と日本語版の変更ログにVKC Componentsの更新を追加
- mkdocs.ymlのナビゲーションとプラグイン設定でタイトルを更新
___
<tr>
<td>
<details>
<summary><strong>VKCHEOCorrespondenceTable.en.md</strong><dd><code>英語版のタイトル変更と説明の削除</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/VKCComponents/VKCHEOCorrespondenceTable.en.md
- タイトルを「VKC/HEO Components …

VKC/HEO コンポーネント 概要：Item, Nodeについて概要を追記

---

docs/AboutVketCloudSDK/SetupAccount.en.md
docs/changelog/changelog-12.3.en.md

Documentation
___
- `SetupAccount`ドキュメントの英訳を追加し、Vket Cloudアカウント登録手順を詳細に記載
- 変更ログに英訳完了の反映と他のドキュメントページのリンクを更新
___
<tr>
<td>
<details>
<summary><strong>SetupAccount.en.md</strong><dd><code>Vket Cloudアカウント設定ガイドの英訳追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/AboutVketCloudSDK/SetupAccount.en.md
- 日本語の手順を英語に翻訳
- Vket Cloudアカウント登録手順の詳細を追加
- 画像のキャプションを英語に変更
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/480/files#d …

SetupAccount: 英訳を追加 (v12.3)

---

docs/changelog/changelog-12.3.en.md
docs/hs/hs_delegate.en.md
docs/hs/hs_statement_control.en.md
docs/hs/hs_string.en.md
docs/hs/hs_system_function_camera.en.md
docs/hs/hs_system_function_commondialog.en.md
docs/hs/hs_var.en.md

Documentation
___
- 英語版のドキュメントにおいて、HeliScript関連のセクションの「英訳作業中」の注記を削除しました。
- デリゲート、ループ制御、文字列操作、カメラ、汎用ダイアログ、変数に関するドキュメントを英訳しました。
- 新しいメソッドや関数の詳細を追加し、各セクションの説明を強化しました。
___
<tr>
<td>
<details>
<summary><strong>changelog-12.3.en.md</strong><dd><code>Update HeliScript documentation status in changelog</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/changelog/changelog-12.3.en.md
<li>Removed "English version WIP" notes from HeliScript sections.<br> <li> Updated information on HeliScript updates for version 12.x.<br>
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/495/files#diff-2edecac36a9625444684d7 …

HeliScript - 英訳を追加 (v12.3) 

---

docs/changelog/changelog-13.4.en.md
docs/changelog/changelog-13.4.ja.md
docs/hs/hs_class_item.en.md
docs/hs/hs_class_item.ja.md

Documentation
___
- 英語と日本語の両方で、Itemクラスの説明を更新しました。
- Itemクラスのインスタンスを取得する方法を明確にしました。
- チェンジログにItemクラスのリンクを追加しました。
___
<tr>
<td>
<details>
<summary><strong>changelog-13.4.en.md</strong><dd><code>Add Item Class link to changelog in English</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Added link to the Item Class documentation.
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/496/files#diff-14c8c02824d74eee1b43874bee086055865ce98e61bcf95f26f17429d8257619">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …

Itemクラスの説明とItemのユーティリティにあるhsItemGetの関数説明を更新 #494

---

docs/changelog/changelog-13.4.en.md
docs/changelog/changelog-13.4.ja.md
docs/hs/hs_class_player.en.md
docs/hs/hs_class_player.ja.md

Documentation, Enhancement
___
- `Player.SetRotate`メソッドに新しい引数`CameraRotate`を追加しました。
- 英語および日本語のドキュメントに変更を反映しました。
- 変更ログに2024年9月6日の更新情報を追加しました。
___
<tr>
<td>
<details>
<summary><strong>changelog-13.4.en.md</strong><dd><code>Update changelog with new Player class argument</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Added a new update entry for September 6, 2024.<br> <li> Documented the addition of a <code>CameraRotate</code> argument to <br><code>Player.SetRotate</code>.<br>
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/498/fi …

PlayerクラスにCameraRotateの引数を追加

---

docs/changelog/changelog-13.4.en.md
docs/changelog/changelog-13.4.ja.md
docs/hs/hs_class_item.en.md
docs/hs/hs_class_item.ja.md

Documentation
___
- 'GetPos'と'GetWorldPos'メソッドの説明を明確化し、使用上の注意を追加しました。
- 英語と日本語の両方のドキュメントに変更を反映しました。
- チェンジログに2024年9月6日の更新内容を追加しました。
___
<tr>
<td>
<details>
<summary><strong>changelog-13.4.en.md</strong><dd><code>Update changelog with 'GetPos' and 'GetWorldPos' changes</code>&nbsp; </dd></summary>
<hr>
<li>Added update entry for September 6, 2024.<br> <li> Noted changes to 'GetPos' and 'GetWorldPos' in the Item class.<br>
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/497/files#diff-14c8c02824d74eee1b43874bee086055865ce98e61bcf95f26f17429d8257619">+8/-0</a>&nbsp; &nbsp; &nbsp; …

GetPosとGetWorldPosの説明の使い分けを説明する

---

docs/changelog/changelog-13.7.en.md
docs/changelog/changelog-13.7.ja.md
docs/releasenote/releasenote-13.8.en.md
docs/releasenote/releasenote-13.8.ja.md
mkdocs.yml

Documentation
___
- バージョン13.8.0のリリースノートを英語と日本語で追加しました。
- 2024年9月12日の更新情報をチェンジログに追加しました。
- mkdocsのナビゲーションにv13.8のリリースノートを追加しました。
___
<tr>
<td>
<details>
<summary><strong>changelog-13.7.en.md</strong><dd><code>Add September 12, 2024 update to changelog (EN)</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/changelog/changelog-13.7.en.md
<li>Added section for September 12, 2024 update.<br> <li> Included link to v13.8 release note.<br>
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/501/files#diff-d9b570fa27d4c4d937d57af4174290a4f68724e3f9a6b00316fa45842effe7a6">+10/-0</a …

Lib13.8リリースノート追加（9/12午前10時公開）

---

docs/VKCComponents/VKCItemActivity.en.md
docs/VKCComponents/VKCItemActivity.ja.md
docs/VKCComponents/VKCItemAreaCollider.en.md
docs/VKCComponents/VKCItemAreaCollider.ja.md
docs/VKCComponents/VKCItemAudio.en.md
docs/VKCComponents/VKCItemAudio.ja.md
docs/VKCComponents/VKCItemBackgroundTexture.en.md
docs/VKCComponents/VKCItemBackgroundTexture.ja.md
docs/VKCComponents/VKCItemCamera.en.md
docs/VKCComponents/VKCItemCamera.ja.md
docs/VKCComponents/VKCItemField.en.md
docs/VKCComponents/VKCItemField.ja.md
docs/VKCComponents/VKCItemObject.en.md
docs/VKCComponents/VKCItemObject.ja.md
docs/changelog/changelog-13.4.en.md
docs/changelog/changelog-13.4.ja.md
docs/changelog/changelog-13.7.en.md
docs/changelog/changelog-13.7.ja.md
docs/hs/hs_class_item.en.md
docs/hs/hs_class_item.ja.md

#503の編集内容をv13.7に移植しました
___
Documentation
___
- 各VKCコンポーネントページに、使用可能なItemクラスのメソッド一覧を追加しました。
- 変更ログを2024年9月13日の更新内容で更新しました。
- `hs_class_item`ドキュメントのノート形式を変更しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><details><summary>20 files</summary><table>
<tr>
<td>
<details>
<summary><strong>VKCItemActivity.en.md</strong><dd><code>Add available methods list to VKC Item Activity</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/VKCComponents/VKCItemActivity.en.md
- Added a list of available methods for VKC Item Activity.
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/508/files#diff-e592fe7698c9dcf7a3da9c5d93426464a311ae57 …

[13.7]Itemクラスページのデフォルト展開と、各コンポーネントページにメソッド一覧追記 

---

docs/VKCComponents/VKCItemField.en.md
docs/VKCComponents/VKCItemField.ja.md
docs/VKCComponents/VKCItemObject.en.md
docs/VKCComponents/VKCItemObject.ja.md
docs/VKCComponents/VKCItemParticle.en.md
docs/VKCComponents/VKCItemParticle.ja.md
docs/VKCComponents/VKCItemPlane.en.md
docs/VKCComponents/VKCItemPlane.ja.md
docs/VKCComponents/VKCItemTextPlane.en.md
docs/VKCComponents/VKCItemTextPlane.ja.md
docs/changelog/changelog-13.4.en.md
docs/changelog/changelog-13.4.ja.md

https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/503 の残
___
Documentation
___
- 各コンポーネントページに使用可能なメソッドの一覧を追加しました。
- `VKCItemField`、`VKCItemObject`、`VKCItemParticle`、`VKCItemPlane`、`VKCItemTextPlane`のドキュメントにメソッド一覧を追記しました。
- changelogに新しいメソッド一覧の追加を記載しました。
- タイポグラフィカルエラーを修正しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><details><summary>12 files</summary><table>
<tr>
<td>
<details>
<summary><strong>VKCItemField.en.md</strong><dd><code>Corrected typographical error in method list.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/VKCComponents/VKCItemField.en.md
- Typographical correction in method list.
</details>
</td>
<td><a …

[13.4]各コンポーネントページにメソッド一覧追記

---

docs/changelog/changelog-13.4.en.md
docs/changelog/changelog-13.4.ja.md
docs/hs/hs_overview.en.md
docs/hs/hs_overview.ja.md

Documentation
___
- HeliScript概要に関する説明文およびリンクを修正しました。
- 英語および日本語のドキュメントにおいて、Playerの振る舞い方の定義リンクを`HEOPlayer`から`VKC Setting Player`に更新しました。
- 変更ログに2024年9月20日の更新情報を追加し、HeliScriptに関連する変更を記載しました。
___
<tr>
<td>
<details>
<summary><strong>changelog-13.4.en.md</strong><dd><code>Update changelog with HeliScript overview fixes</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Added a new update entry for September 20, 2024.<br> <li> Included changes related to HeliScript overview.<br> <li> Fixed descriptions and links.<br>
</details>
</td>
<td><a …

HeliScript概要: リンク修正

---

docs/changelog/changelog-13.7.en.md
docs/changelog/changelog-13.7.ja.md
docs/index.en.md
docs/index.ja.md

Documentation
___
- VketCloudSDKの公式マニュアルにWorld Builderの紹介を追加しました。
- 英語および日本語のインデックスページにWorld Builderのセクションを追加し、マニュアルへのリンクを提供しました。
- 2024年10月4日の更新情報として、World Builderの紹介を含む変更を記載しました。
___
<tr>
<td>
<details>
<summary><strong>changelog-13.7.en.md</strong><dd><code>Add October 4, 2024 update entry with World Builder</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/changelog/changelog-13.7.en.md
<li>Added a new update entry for October 4, 2024.<br> <li> Mentioned the addition of World Builder introduction.<br>
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/519/files#diff-d9b570fa27d4c4d937d57af4174 …

index: World Builderの紹介を追記

---

docs/ExternalAPI/BrokerAPI.en.md
docs/ExternalAPI/BrokerAPI.ja.md
docs/changelog/changelog-14.2.en.md
docs/changelog/changelog-14.2.ja.md
mkdocs.yml

Documentation
___
- 英語および日本語のドキュメントで、`api.broker`から`heliport.v3.api.broker`へのメソッド呼び出しを更新しました。
- SDKバージョン14.2の変更ログを英語と日本語で追加しました。
- mkdocsのナビゲーションにバージョン14.2の変更ログを追加しました。
___
<tr>
<td>
<details>
<summary><strong>BrokerAPI.en.md</strong><dd><code>Update Broker API method calls in English documentation</code>&nbsp; &nbsp; </dd></summary>
<hr>
docs/ExternalAPI/BrokerAPI.en.md
<li>Updated API method calls to use <code>heliport.v3.api.broker</code>.<br> <li> Modified example code for registering agreements and connecting to <br>external API.<br>
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/535/files#diff-9c38ff677fcec2bb7 …

BrokerAPI: サンプルコード修正(14.2)

---

mkdocs.yml

Bug fix
___
- `mkdocs.yml`ファイル内のホームページURLを修正しました。
- 古いURL `https://www.hikky.co.jp/vketcloud` を新しいURL `https://cloud.vket.com/creator` に変更しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>mkdocs.yml</strong><dd><code>ホームページURLの修正</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
mkdocs.yml
- ホームページのURLを修正
- 古いURLを新しいURLに置き換え
</details>
</td>
<td><a …

【14.2】ホームページのURLを修正

---

mkdocs.yml

Bug fix
___
- `mkdocs.yml`ファイルのホームページURLを修正しました。
- URLを`https://cloud.vket.com/creator`に更新しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>mkdocs.yml</strong><dd><code>ホームページのURLを修正</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
mkdocs.yml
- ホームページのURLを修正
- URLを`https://cloud.vket.com/creator`に更新
</details>
</td>
<td><a …

【13.7】 ホームページのURLを修正

---

docs/hs/hs_system_function_gui.en.md
docs/hs/hs_system_function_gui.ja.md

Documentation
___
- `hsAddGUIButton`関数の説明を修正し、正しいシグネチャを反映
- 英語および日本語ドキュメントの関数シグネチャを更新
- 関数の引数リストに新しい引数を追加
___
<tr>
<td>
<details>
<summary><strong>hs_system_function_gui.en.md</strong><dd><code>英語ドキュメントの関数シグネチャ修正</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/hs/hs_system_function_gui.en.md
- `hsAddGUIButton`の関数シグネチャを修正
- 新しい引数を追加し、説明を更新
</details>
</td>
<td><a …

sdk-13.4 - hs_system_function_gui: hsAddGUIButtonの関数説明を修正

---

docs/hs/hs_system_function_gui.en.md
docs/hs/hs_system_function_gui.ja.md

Documentation
___
- `hsAddGUIButton`関数の説明を修正し、正確なシグネチャを反映。
- 英語および日本語ドキュメントの関数定義を更新。
- 新しい引数を追加し、詳細な説明を提供。
___
<tr>
<td>
<details>
<summary><strong>hs_system_function_gui.en.md</strong><dd><code>英語ドキュメントの関数シグネチャを更新</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/hs/hs_system_function_gui.en.md
- `hsAddGUIButton`の関数シグネチャを修正。
- 新しい引数を追加し、説明を更新。
- ボタンタイプGUIの詳細を明確化。
</details>
</td>
<td><a …

sdk-14.2 - hs_system_function_gui: hsAddGUIButtonの関数説明を修正

---

docs/hs/hs_system_function_gui.en.md
docs/hs/hs_system_function_gui.ja.md

Documentation
___
- `hsAddGUIButton`関数の説明を修正し、正確なシグネチャを反映。
- 英語および日本語ドキュメントでの関数定義の更新。
- 新しい引数を追加し、詳細な説明を提供。
___
<tr>
<td>
<details>
<summary><strong>hs_system_function_gui.en.md</strong><dd><code>英語ドキュメントでの`hsAddGUIButton`関数説明更新</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/hs/hs_system_function_gui.en.md
- `hsAddGUIButton`関数のシグネチャを修正。
- 新しい引数を追加し、説明を更新。
- 関数の目的を明確化。
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/589/files#diff-48f2f2b61e22792ab5d958b3a6c0907 …

sdk-13.7 - hs_system_function_gui: hsAddGUIButtonの関数説明を修正

---

mkdocs.yml

Bug fix
___
- 修正: `mkdocs.yml`ファイル内の全角スペースを半角スペースに変更
- ドキュメントナビゲーションのフォーマットエラーを解消
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>mkdocs.yml</strong><dd><code>全角スペースを半角スペースに修正</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
mkdocs.yml
- 全角スペースを半角スペースに修正
- ドキュメントナビゲーションのフォーマットを統一
</details>
</td>
<td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/591/files#diff-98d0f806abc9af24e6a7c545d3d77 …

mkdocs.yml: 全角スペーストル
